/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        App.readJSFile("gates.js");
    }

    public static String readJSFile(String filename){

        Path path= Paths.get("gates.js");
        try{

            BufferedReader reader= Files.newBufferedReader(path);
            String line= reader.readLine();
            char lastChar=line.charAt(line.length()-1);
            String errorMessage="Missing semicolon.";
            int lineCount=0;
            while(line!= null){
                line= reader.readLine();
                if(line.length()!=0 || lastChar=='{'||lastChar=='}'||lastChar==';'||line.contains("if")||line.contains("else")){
                    System.out.println(line);
                    lineCount++;
                } if(lastChar!=';'){
                    System.out.println("Line "+ lineCount+": "+errorMessage);
                }
                line =reader.readLine();
             }
        }catch(IOException e){
            e.printStackTrace();
        }finally {
            System.out.println("The end of the program");
        }
        return filename;
    }
}

