/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();

    }
    @Test
    public void constructorTestRes(){
        Restaurant test = new Restaurant("fourGuys", 3.5 ,"$");
        String expectedName = "fourGuys";
        assertEquals(expectedName,test.getName());
        assertEquals(3.5,test.getNumOfStars());
        assertEquals("$",test.getPrice());
    }
    @Test
    public void toStringMethodTestRes() {
        Restaurant test = new Restaurant("fourGuys", 3.5 ,"$");
        assertEquals("Restaurant{name='fourGuys', numOfStars=3.5, price='$'}",String.valueOf(test));

    }
    @Test
    public void addReviewsTest(){
        Restaurant test = new Restaurant("fourGuys", 3.5 ,"$");
        Review test1 = new Review("best burger ever","Rawan Alazazi",5);
        Review test2 = new Review("nice service and delicious food","Liam Hardy",10);
        test.addReview(test1);
        test.addReview(test2);
        assertEquals(2, test.getReviews().size(),"return true if add review");
    }
    @Test
    public void constructorTestRev(){
        Review test = new Review("best burger ever", "Rawan Alazazi",5);
        assertEquals("best burger ever",test.getBody());
        assertEquals("Rawan Alazazi",test.getAuthor());
        assertEquals(5,test.getNumOfStars());

    }
    @Test
    public void testRev(){
        Review test = new Review("I like this restaurant, but their prices are very high","Sara Tomas",3.5);
        assertEquals("Review{body='I like this restaurant, but their prices are very high', author='Sara Tomas', numOfStars=3.5}",String.valueOf(test));    }

}
