/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test public void testEmptyFile() {
        String fileData = App.readJSFile("src/test/resources/empty.js");
        assertTrue(!fileData.contains("Missing semicolon."));
    }

    @Test
    public void testNoErrorsFile() {
        String fileData = App.readJSFile("src/test/resources/noErrors.js");
        assertTrue(!fileData.contains("Missing semicolon."));
    }
    @Test
    public void oneErrorTest() {
        String fileData = App.readJSFile("src/test/resources/oneError.js");
        assertTrue(fileData.contains("Missing semicolon."));
    }

    @Test
    public void fewErrorsTest() {
        String fileData = App.readJSFile("src/test/resources/fewErrors.js");
        assertTrue(fileData.contains("Missing semicolon."));
    }

    @Test
    public void manyErrorsTest() {
        String fileData = App.readJSFile("src/test/resources/manyErrors.js");
        assertTrue(fileData.contains("Missing semicolon."));
    }


}
